application: grand-century-576
version: 1
runtime: python27
api_version: 1
threadsafe: true

includes:
- demos/quick-start/app.yaml

handlers:
- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /bootstrap
  static_dir: static/bootstrap

- url: /fontawesome
  static_dir: static/fontawesome

- url: /oauth2callback.*
  script: main.app

- url: /
  script: main.app

libraries:
- name: jinja2
  version: latest

builtins:
- deferred: on

inbound_services:
- warmup
